services:
  tutoring:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: MakeIt_DB
    ports:
      - "3306:3306"
    volumes:
      - .my/sql-data:/var/lib/mysql